#!/usr/bin/env bash
# Publish a self-hosted Computer release into $RAFT_COMPUTER_WEB_ROOT (nginx
# serves it at /computer/). Contract: "D 先提供版本目录、二进制及全部附属文件
# 并校验完整，再原子切换 latest manifest" — this script validates everything
# BEFORE touching the live root, publishes the version directory, then flips
# the root manifest.json (the "latest" pointer) atomically last.
#
# Usage: publish-computer.sh <staging-dir>
#
# <staging-dir> mirrors the web root layout:
#   <staging-dir>/<version>/manifest.json   per-version manifest (targets + photonWasm)
#   <staging-dir>/<version>/...             binaries and sidecars listed in that manifest
#   <staging-dir>/install.sh                entry script (optional; published when present)
#   <staging-dir>/install.ps1               entry script (optional; published when present)
# Exactly one <version>/ directory must exist; its name is the published version.
# The root manifest.json is generated by this script as {"version": "<version>"}.
#
# Immutability rules (task #8, Anna-mac):
#   - an existing <version>/ dir with DIFFERENT content  -> refused (exit 1)
#   - an existing <version>/ dir with IDENTICAL content  -> idempotent no-op
#   - a corrupted/incomplete staging dir                  -> refused before any
#     live change, so the current latest pointer is never modified.
# Entry scripts are replaced atomically when their content changes (they are
# the "current contract" surface, not immutable artifacts).
set -eu
source "$(dirname "$0")/lib.sh"

STAGING=${1:?usage: publish-computer.sh <staging-dir> (see header comment)}
[ -d "$STAGING" ] || die "staging dir not found: $STAGING"
STAGING=$(cd "$STAGING" && pwd)
ROOT=$RAFT_COMPUTER_WEB_ROOT
mkdir -p "$ROOT"

# --- collect the single version dir -------------------------------------------------
versions=()
for f in "$STAGING"/*/; do
  f=${f%/}; [ -d "$f" ] || continue
  case "$(basename "$f")" in
    [0-9]*) versions+=("$(basename "$f")") ;;
  esac
done
[ "${#versions[@]}" -eq 1 ] || die "staging must contain exactly one <version>/ dir (found: ${versions[*]:-none})"
VERSION=${versions[0]}
VDIR=$STAGING/$VERSION

# --- validate the staging release against its own manifest ---------------------------
# Every file the manifest references (targets[].file, optional targets[].gz.file,
# photonWasm.file) must exist with the exact sha256 and size_bytes. Unknown
# extra files are refused too: a publish must be a complete, closed set.
python3 - "$VDIR" "$VERSION" <<'PY' || die "staging validation failed for $VERSION (nothing published)"
import hashlib, json, os, sys

vdir, version = sys.argv[1], sys.argv[2]
try:
    manifest = json.load(open(os.path.join(vdir, "manifest.json")))
except Exception as e:
    print(f"manifest.json unreadable: {e}"); sys.exit(1)

referenced = []
def want(rel, sha, size, what):
    path = os.path.join(vdir, rel)
    if "/" in rel or rel.startswith("."):
        print(f"{what}: refusing path outside the version dir: {rel}"); sys.exit(1)
    if not os.path.isfile(path):
        print(f"{what}: missing file {rel}"); sys.exit(1)
    data = open(path, "rb").read()
    if sha and hashlib.sha256(data).hexdigest() != sha.lower():
        print(f"{what}: sha256 mismatch for {rel}"); sys.exit(1)
    if size is not None and len(data) != size:
        print(f"{what}: size mismatch for {rel} (manifest {size}, actual {len(data)})"); sys.exit(1)
    referenced.append(rel)

targets = manifest.get("targets")
if not isinstance(targets, dict) or not targets:
    print("manifest has no targets object"); sys.exit(1)
for target, entry in sorted(targets.items()):
    if not isinstance(entry, dict) or not entry.get("file"):
        print(f"target {target}: missing file field"); sys.exit(1)
    want(entry["file"], entry.get("sha256"), entry.get("size_bytes"), f"target {target}")
    gz = entry.get("gz")
    if isinstance(gz, dict) and gz.get("file"):
        want(gz["file"], gz.get("sha256"), gz.get("size_bytes"), f"target {target} gz")

photon = manifest.get("photonWasm")
if not isinstance(photon, dict) or not photon.get("file"):
    print("manifest missing photonWasm entry"); sys.exit(1)
want(photon["file"], photon.get("sha256"), photon.get("size_bytes"), "photonWasm")

actual = {f for f in os.listdir(vdir) if f != "manifest.json"}
extra = actual - set(referenced)
if extra:
    print(f"unreferenced files in version dir: {', '.join(sorted(extra))}"); sys.exit(1)
print(f"validated {len(referenced)} artifact(s) for {version}")
PY

# --- publish the version dir: identical -> no-op, divergent -> refuse ----------------
dest=$ROOT/$VERSION
if [ -d "$dest" ]; then
  if diff -r "$VDIR" "$dest" >/dev/null 2>&1; then
    log "version $VERSION already published with identical content (idempotent)"
  else
    die "version $VERSION already published with DIFFERENT content; version dirs are immutable — bump the version instead"
  fi
else
  tmp=$ROOT/.publish-$VERSION.$$
  trap 'rm -rf "$tmp"' EXIT
  cp -R "$VDIR" "$tmp"
  # Re-verify in place so a partial copy can never be promoted.
  if ! diff -r "$VDIR" "$tmp" >/dev/null 2>&1; then
    rm -rf "$tmp"; die "copy verification failed for $VERSION (nothing published)"
  fi
  chmod -R a-w "$tmp" 2>/dev/null || true
  mv "$tmp" "$dest"
  trap - EXIT
  log "published immutable version dir $dest"
fi

# --- entry scripts: atomic replace when content differs ------------------------------
for script in install.sh install.ps1; do
  src=$STAGING/$script
  [ -f "$src" ] || continue
  dst=$ROOT/$script
  if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
    log "$script unchanged"
  else
    tmp=$ROOT/.$script.$$
    cp "$src" "$tmp"
    if command -v shellcheck >/dev/null 2>&1 && [ "$script" = install.sh ]; then
      shellcheck "$tmp" || { rm -f "$tmp"; die "install.sh failed shellcheck (nothing else changed)"; }
    fi
    mv -f "$tmp" "$dst"
    log "$script updated (sha256 $(shasum -a 256 "$dst" | cut -c1-12))"
  fi
done

# --- flip the latest pointer LAST ----------------------------------------------------
python3 - "$ROOT" "$VERSION" <<'PY' || die "latest pointer flip failed (version dir remains published)"
import json, os, sys
root, version = sys.argv[1], sys.argv[2]
tmp = os.path.join(root, ".manifest.json.flip")
with open(tmp, "w") as f:
    json.dump({"version": version}, f)
    f.write("\n")
json.load(open(tmp))  # parse it back before it becomes the pointer
os.replace(tmp, os.path.join(root, "manifest.json"))
print(f"latest pointer -> {version}")
PY

# --- read back ------------------------------------------------------------------------
python3 -c "import json,sys; print('latest is now', json.load(open('$ROOT/manifest.json'))['version'])"
log "publish complete: https://<your-origin>/computer/ serves $VERSION"
