// Code generated from packages/shared/src/piBuiltinModels.generated.ts
// and packages/shared/src/generated/runtimeProviderDisplayNames.ts.
// Preset order is Object.keys insertion order of PI_BUILTIN_PROVIDER_API_KEY_ENV_KEYS.
// Do not edit by hand; regenerate from those sources.
package runtimecatalog

type builtinModel struct {
	ID    string
	Label string
}

type builtinProvider struct {
	ID      string
	Label   string
	Default string
	Models  []builtinModel
}

func bm(id, label string) builtinModel { return builtinModel{ID: id, Label: label} }

var builtinPresetProviders = []builtinProvider{
	{
		ID: "deepseek", Label: "DeepSeek", Default: "deepseek/deepseek-v4-pro",
		Models: []builtinModel{
			bm("deepseek/deepseek-v4-pro", "DeepSeek V4 Pro"),
			bm("deepseek/deepseek-v4-flash", "DeepSeek V4 Flash"),
			bm("deepseek/deepseek-v4-flash-vision-exp", "DeepSeek V4 Flash Vision Exp"),
		},
	},
	{
		ID: "minimax", Label: "MiniMax", Default: "minimax/MiniMax-M2.7",
		Models: []builtinModel{
			bm("minimax/MiniMax-M3", "MiniMax-M3"),
			bm("minimax/MiniMax-M2.7", "MiniMax-M2.7"),
			bm("minimax/MiniMax-M2.7-highspeed", "MiniMax-M2.7-highspeed"),
		},
	},
	{
		ID: "minimax-cn", Label: "MiniMax CN", Default: "minimax-cn/MiniMax-M2.7",
		Models: []builtinModel{
			bm("minimax-cn/MiniMax-M3", "MiniMax-M3"),
			bm("minimax-cn/MiniMax-M2.7", "MiniMax-M2.7"),
			bm("minimax-cn/MiniMax-M2.7-highspeed", "MiniMax-M2.7-highspeed"),
		},
	},
	{
		ID: "zai", Label: "Z.AI", Default: "zai/glm-5.3",
		Models: []builtinModel{
			bm("zai/glm-5.3", "GLM-5.3"),
			bm("zai/glm-5.2", "GLM-5.2"),
			bm("zai/glm-4.7", "GLM-4.7"),
			bm("zai/glm-5.3-highspeed", "GLM-5.3 Highspeed"),
			bm("zai/glm-5.3-flash", "GLM-5.3-Flash"),
			bm("zai/glm-5.2-highspeed", "GLM-5.2 Highspeed"),
			bm("zai/glm-5-turbo", "GLM-5-Turbo"),
		},
	},
	{
		ID: "zai-coding-cn", Label: "Z.AI Coding CN", Default: "zai-coding-cn/glm-5.3",
		Models: []builtinModel{
			bm("zai-coding-cn/glm-5.3", "GLM-5.3"),
			bm("zai-coding-cn/glm-5.2", "GLM-5.2"),
			bm("zai-coding-cn/glm-5.1", "GLM-5.1"),
			bm("zai-coding-cn/glm-4.7", "GLM-4.7"),
			bm("zai-coding-cn/glm-4.6v", "GLM-4.6V"),
			bm("zai-coding-cn/glm-5.3-highspeed", "GLM-5.3 Highspeed"),
			bm("zai-coding-cn/glm-5.3-flash", "GLM-5.3-Flash"),
			bm("zai-coding-cn/glm-5.2-highspeed", "GLM-5.2 Highspeed"),
			bm("zai-coding-cn/glm-5-turbo", "GLM-5-Turbo"),
			bm("zai-coding-cn/glm-5v-turbo", "GLM-5V-Turbo"),
		},
	},
	{
		ID: "moonshotai", Label: "Moonshot AI", Default: "moonshotai/kimi-k2.6",
		Models: []builtinModel{
			bm("moonshotai/kimi-k2.7-code", "Kimi K2.7 Code"),
			bm("moonshotai/kimi-k2-thinking", "Kimi K2 Thinking"),
			bm("moonshotai/kimi-k2.7-code-highspeed", "Kimi K2.7 Code HighSpeed"),
			bm("moonshotai/kimi-k2-thinking-turbo", "Kimi K2 Thinking Turbo"),
			bm("moonshotai/kimi-k2-0905-preview", "Kimi K2 0905"),
			bm("moonshotai/kimi-k2-0711-preview", "Kimi K2 0711"),
			bm("moonshotai/kimi-k3", "Kimi K3"),
			bm("moonshotai/kimi-k2.6", "Kimi K2.6"),
			bm("moonshotai/kimi-k2.5", "Kimi K2.5"),
			bm("moonshotai/kimi-k2-turbo-preview", "Kimi K2 Turbo"),
		},
	},
	{
		ID: "moonshotai-cn", Label: "Moonshot AI CN", Default: "moonshotai-cn/kimi-k2.6",
		Models: []builtinModel{
			bm("moonshotai-cn/kimi-k2.7-code", "Kimi K2.7 Code"),
			bm("moonshotai-cn/kimi-k2-thinking", "Kimi K2 Thinking"),
			bm("moonshotai-cn/kimi-k2.7-code-highspeed", "Kimi K2.7 Code HighSpeed"),
			bm("moonshotai-cn/kimi-k2-thinking-turbo", "Kimi K2 Thinking Turbo"),
			bm("moonshotai-cn/kimi-k2-0905-preview", "Kimi K2 0905"),
			bm("moonshotai-cn/kimi-k2-0711-preview", "Kimi K2 0711"),
			bm("moonshotai-cn/kimi-k3", "Kimi K3"),
			bm("moonshotai-cn/kimi-k2.6", "Kimi K2.6"),
			bm("moonshotai-cn/kimi-k2.5", "Kimi K2.5"),
			bm("moonshotai-cn/kimi-k2-turbo-preview", "Kimi K2 Turbo"),
		},
	},
	{
		ID: "kimi-coding", Label: "Kimi For Coding", Default: "kimi-coding/kimi-for-coding",
		Models: []builtinModel{
			bm("kimi-coding/k3-256k", "Kimi K3-256K"),
			bm("kimi-coding/k3", "Kimi K3"),
			bm("kimi-coding/kimi-for-coding", "Kimi K2.7 Code"),
			bm("kimi-coding/kimi-for-coding-highspeed", "Kimi For Coding HighSpeed"),
		},
	},
	{
		ID: "qwen-token-plan", Label: "Qwen Token Plan", Default: "qwen-token-plan/qwen3.7-max",
		Models: []builtinModel{
			bm("qwen-token-plan/deepseek-v4-pro-0813", "DeepSeek V4 Pro 0813"),
			bm("qwen-token-plan/deepseek-v4-pro", "DeepSeek V4 Pro"),
			bm("qwen-token-plan/qwen3.8-max", "Qwen3.8 Max"),
			bm("qwen-token-plan/qwen3.7-max", "Qwen3.7 Max"),
			bm("qwen-token-plan/kimi-k2.7-code", "Kimi K2.7 Code"),
			bm("qwen-token-plan/glm-5.2", "GLM-5.2"),
			bm("qwen-token-plan/glm-5.1", "GLM-5.1"),
			bm("qwen-token-plan/glm-5", "GLM-5"),
			bm("qwen-token-plan/qwen3.7-plus", "Qwen3.7 Plus"),
			bm("qwen-token-plan/qwen3.6-plus", "Qwen3.6 Plus"),
			bm("qwen-token-plan/deepseek-v3.2", "DeepSeek V3.2"),
			bm("qwen-token-plan/kimi-k2.6", "Kimi K2.6"),
			bm("qwen-token-plan/kimi-k2.5", "Kimi K2.5"),
			bm("qwen-token-plan/MiniMax-M2.5", "MiniMax-M2.5"),
			bm("qwen-token-plan/deepseek-v4-flash-0731", "DeepSeek V4 Flash 0731"),
			bm("qwen-token-plan/deepseek-v4-flash", "DeepSeek V4 Flash"),
			bm("qwen-token-plan/qwen3.8-flash", "Qwen3.8 Flash"),
			bm("qwen-token-plan/qwen3.6-flash", "Qwen3.6 Flash"),
		},
	},
	{
		ID: "qwen-token-plan-cn", Label: "Qwen Token Plan CN", Default: "qwen-token-plan-cn/qwen3.7-max",
		Models: []builtinModel{
			bm("qwen-token-plan-cn/deepseek-v4-pro-0813", "DeepSeek V4 Pro 0813"),
			bm("qwen-token-plan-cn/deepseek-v4-pro", "DeepSeek V4 Pro"),
			bm("qwen-token-plan-cn/qwen3.8-max", "Qwen3.8 Max"),
			bm("qwen-token-plan-cn/qwen3.7-max", "Qwen3.7 Max"),
			bm("qwen-token-plan-cn/kimi-k2.7-code", "Kimi K2.7 Code"),
			bm("qwen-token-plan-cn/glm-5.2", "GLM-5.2"),
			bm("qwen-token-plan-cn/glm-5.1", "GLM-5.1"),
			bm("qwen-token-plan-cn/glm-5", "GLM-5"),
			bm("qwen-token-plan-cn/qwen3.7-plus", "Qwen3.7 Plus"),
			bm("qwen-token-plan-cn/qwen3.6-plus", "Qwen3.6 Plus"),
			bm("qwen-token-plan-cn/deepseek-v3.2", "DeepSeek V3.2"),
			bm("qwen-token-plan-cn/kimi-k2.6", "Kimi K2.6"),
			bm("qwen-token-plan-cn/kimi-k2.5", "Kimi K2.5"),
			bm("qwen-token-plan-cn/MiniMax-M2.5", "MiniMax-M2.5"),
			bm("qwen-token-plan-cn/deepseek-v4-flash-0731", "DeepSeek V4 Flash 0731"),
			bm("qwen-token-plan-cn/deepseek-v4-flash", "DeepSeek V4 Flash"),
			bm("qwen-token-plan-cn/qwen3.8-flash", "Qwen3.8 Flash"),
			bm("qwen-token-plan-cn/qwen3.6-flash", "Qwen3.6 Flash"),
		},
	},
	{
		ID: "openrouter", Label: "OpenRouter", Default: "openrouter/moonshotai/kimi-k2.6",
		Models: []builtinModel{
			bm("openrouter/anthropic/claude-fable-5.1", "Anthropic: Claude Fable 5.1"),
			bm("openrouter/anthropic/claude-fable-5.1:batch", "Anthropic: Claude Fable 5.1 (batch)"),
			bm("openrouter/anthropic/claude-fable-5", "Anthropic: Claude Fable 5"),
			bm("openrouter/anthropic/claude-fable-5:batch", "Anthropic: Claude Fable 5 (batch)"),
			bm("openrouter/~anthropic/claude-fable-latest", "Anthropic: Claude Fable Latest"),
			bm("openrouter/anthropic/claude-opus-5", "Claude Opus 5"),
			bm("openrouter/anthropic/claude-opus-5:batch", "Claude Opus 5 (batch)"),
			bm("openrouter/anthropic/claude-opus-4.8", "Anthropic: Claude Opus 4.8"),
			bm("openrouter/anthropic/claude-opus-4.8:batch", "Anthropic: Claude Opus 4.8 (batch)"),
			bm("openrouter/anthropic/claude-opus-4.7", "Anthropic: Claude Opus 4.7"),
			bm("openrouter/anthropic/claude-opus-4.7:batch", "Anthropic: Claude Opus 4.7 (batch)"),
			bm("openrouter/anthropic/claude-opus-4.6", "Anthropic: Claude Opus 4.6"),
			bm("openrouter/anthropic/claude-opus-4.6:batch", "Anthropic: Claude Opus 4.6 (batch)"),
			bm("openrouter/anthropic/claude-opus-4.5", "Anthropic: Claude Opus 4.5"),
			bm("openrouter/anthropic/claude-opus-4.5:batch", "Anthropic: Claude Opus 4.5 (batch)"),
			bm("openrouter/anthropic/claude-opus-4.1", "Anthropic: Claude Opus 4.1"),
			bm("openrouter/anthropic/claude-opus-4.1:batch", "Anthropic: Claude Opus 4.1 (batch)"),
			bm("openrouter/anthropic/claude-opus-4", "Anthropic: Claude Opus 4"),
			bm("openrouter/~anthropic/claude-opus-latest", "Anthropic: Claude Opus Latest"),
			bm("openrouter/anthropic/claude-sonnet-5", "Anthropic: Claude Sonnet 5"),
			bm("openrouter/anthropic/claude-sonnet-5:batch", "Anthropic: Claude Sonnet 5 (batch)"),
			bm("openrouter/anthropic/claude-sonnet-4.6", "Anthropic: Claude Sonnet 4.6"),
			bm("openrouter/anthropic/claude-sonnet-4.6:batch", "Anthropic: Claude Sonnet 4.6 (batch)"),
			bm("openrouter/anthropic/claude-sonnet-4.5", "Anthropic: Claude Sonnet 4.5"),
			bm("openrouter/anthropic/claude-sonnet-4.5:batch", "Anthropic: Claude Sonnet 4.5 (batch)"),
			bm("openrouter/anthropic/claude-sonnet-4", "Anthropic: Claude Sonnet 4"),
			bm("openrouter/~anthropic/claude-sonnet-latest", "Anthropic Claude Sonnet Latest"),
			bm("openrouter/anthropic/claude-haiku-4.5", "Anthropic: Claude Haiku 4.5"),
			bm("openrouter/anthropic/claude-haiku-4.5:batch", "Anthropic: Claude Haiku 4.5 (batch)"),
			bm("openrouter/anthropic/claude-3-haiku", "Anthropic: Claude 3 Haiku"),
			bm("openrouter/~anthropic/claude-haiku-latest", "Anthropic Claude Haiku Latest"),
			bm("openrouter/openai/gpt-5.1-codex-max", "OpenAI: GPT-5.1-Codex-Max"),
			bm("openrouter/kwaipilot/kat-coder-pro-v2.5", "Kwaipilot: KAT-Coder-Pro V2.5"),
			bm("openrouter/kwaipilot/kat-coder-pro-v2", "Kwaipilot: KAT-Coder-Pro V2"),
			bm("openrouter/qwen/qwen3-max-thinking", "Qwen: Qwen3 Max Thinking"),
			bm("openrouter/qwen/qwen3.8-max-0902", "Qwen: Qwen3.8 Max (0902)"),
			bm("openrouter/deepseek/deepseek-v4-pro-0813", "DeepSeek: DeepSeek V4 Pro 0813"),
			bm("openrouter/deepseek/deepseek-v4-pro-0813:batch", "DeepSeek: DeepSeek V4 Pro 0813 (batch)"),
			bm("openrouter/nvidia/nemotron-3-ultra-550b-a55b", "NVIDIA: Nemotron 3 Ultra"),
			bm("openrouter/deepseek/deepseek-v4-pro", "DeepSeek: DeepSeek V4 Pro 0423"),
			bm("openrouter/google/gemini-2.5-pro-preview", "Google: Gemini 2.5 Pro Preview 06-05"),
			bm("openrouter/openai/gpt-6-astra-pro", "OpenAI: GPT-6 Astra Pro"),
			bm("openrouter/openai/gpt-6-astra-pro:batch", "OpenAI: GPT-6 Astra Pro (batch)"),
			bm("openrouter/google/gemini-2.5-pro-preview-05-06", "Google: Gemini 2.5 Pro Preview 05-06"),
			bm("openrouter/openai/gpt-5.6-luna-pro", "OpenAI: GPT-5.6 Luna Pro"),
			bm("openrouter/openai/gpt-5.6-luna-pro:batch", "OpenAI: GPT-5.6 Luna Pro (batch)"),
			bm("openrouter/openai/gpt-5.6-sol-pro", "OpenAI: GPT-5.6 Sol Pro"),
			bm("openrouter/openai/gpt-5.6-sol-pro:batch", "OpenAI: GPT-5.6 Sol Pro (batch)"),
			bm("openrouter/openai/gpt-5.6-terra-pro", "OpenAI: GPT-5.6 Terra Pro"),
			bm("openrouter/openai/gpt-5.6-terra-pro:batch", "OpenAI: GPT-5.6 Terra Pro (batch)"),
			bm("openrouter/openai/gpt-5.5-pro", "OpenAI: GPT-5.5 Pro"),
			bm("openrouter/openai/gpt-5.5-pro:batch", "OpenAI: GPT-5.5 Pro (batch)"),
			bm("openrouter/openai/gpt-5.4-pro", "OpenAI: GPT-5.4 Pro"),
			bm("openrouter/openai/gpt-5.4-pro:batch", "OpenAI: GPT-5.4 Pro (batch)"),
			bm("openrouter/openai/gpt-5.2-pro", "OpenAI: GPT-5.2 Pro"),
			bm("openrouter/openai/gpt-5.2-pro:batch", "OpenAI: GPT-5.2 Pro (batch)"),
			bm("openrouter/openai/gpt-5-pro", "OpenAI: GPT-5 Pro"),
			bm("openrouter/openai/gpt-5-pro:batch", "OpenAI: GPT-5 Pro (batch)"),
			bm("openrouter/upstage/solar-pro4", "Upstage: Solar Pro 4"),
			bm("openrouter/qwen/qwen3.7-max", "Qwen: Qwen3.7 Max"),
			bm("openrouter/qwen/qwen3.6-max-preview", "Qwen: Qwen3.6 Max Preview"),
			bm("openrouter/google/gemini-3.1-pro-preview", "Google: Gemini 3.1 Pro Preview"),
			bm("openrouter/google/gemini-3.1-pro-preview:batch", "Google: Gemini 3.1 Pro Preview (batch)"),
			bm("openrouter/google/gemini-3.1-pro-preview-customtools", "Google: Gemini 3.1 Pro Preview Custom Tools"),
			bm("openrouter/openai/o3-pro", "OpenAI: o3 Pro"),
			bm("openrouter/qwen/qwen3-max", "Qwen: Qwen3 Max"),
			bm("openrouter/upstage/solar-pro-3", "Upstage: Solar Pro 3"),
			bm("openrouter/google/gemini-2.5-pro", "Google: Gemini 2.5 Pro"),
			bm("openrouter/google/gemini-2.5-pro:batch", "Google: Gemini 2.5 Pro (batch)"),
			bm("openrouter/xiaomi/mimo-v2.5-pro", "Xiaomi: MiMo-V2.5-Pro"),
			bm("openrouter/nex-agi/nex-n2-pro", "Nex AGI: Nex-N2-Pro"),
			bm("openrouter/amazon/nova-premier-v1", "Amazon: Nova Premier 1.0"),
			bm("openrouter/amazon/nova-pro-v1", "Amazon: Nova Pro 1.0"),
			bm("openrouter/~google/gemini-pro-latest", "Google Gemini Pro Latest"),
			bm("openrouter/sakana/fugu-ultra", "Sakana: Fugu Ultra"),
			bm("openrouter/arcee-ai/trinity-large-thinking", "Arcee AI: Trinity Large Thinking"),
			bm("openrouter/qwen/qwen3-coder", "Qwen: Qwen3 Coder 480B A35B"),
			bm("openrouter/qwen/qwen3-coder-30b-a3b-instruct", "Qwen: Qwen3 Coder 30B A3B Instruct"),
			bm("openrouter/openai/gpt-5.3-codex", "OpenAI: GPT-5.3-Codex"),
			bm("openrouter/openai/gpt-5.2-codex", "OpenAI: GPT-5.2-Codex"),
			bm("openrouter/openai/gpt-5.1-codex", "OpenAI: GPT-5.1-Codex"),
			bm("openrouter/qwen/qwen3-coder-next", "Qwen: Qwen3 Coder Next"),
			bm("openrouter/qwen/qwen3-coder-plus", "Qwen: Qwen3 Coder Plus"),
			bm("openrouter/moonshotai/kimi-k2.7-code", "MoonshotAI: Kimi K2.7 Code"),
			bm("openrouter/bytedance-seed/seed-2.0-code", "ByteDance Seed: Seed-2.0-Code"),
			bm("openrouter/qwen/qwen3-235b-a22b-thinking-2507", "Qwen: Qwen3 235B A22B Thinking 2507"),
			bm("openrouter/qwen/qwen3-30b-a3b-thinking-2507", "Qwen: Qwen3 30B A3B Thinking 2507"),
			bm("openrouter/qwen/qwen3-vl-235b-a22b-thinking", "Qwen: Qwen3 VL 235B A22B Thinking"),
			bm("openrouter/qwen/qwen3-next-80b-a3b-thinking", "Qwen: Qwen3 Next 80B A3B Thinking"),
			bm("openrouter/qwen/qwen3-vl-30b-a3b-thinking", "Qwen: Qwen3 VL 30B A3B Thinking"),
			bm("openrouter/qwen/qwen3-vl-8b-thinking", "Qwen: Qwen3 VL 8B Thinking"),
			bm("openrouter/google/gemini-3-pro-image", "Google: Nano Banana Pro (Gemini 3 Pro Image)"),
			bm("openrouter/moonshotai/kimi-k2-thinking", "MoonshotAI: Kimi K2 Thinking"),
			bm("openrouter/thinkingmachines/inkling", "Thinking Machines: Inkling"),
			bm("openrouter/thinkingmachines/inkling:batch", "Thinking Machines: Inkling (batch)"),
			bm("openrouter/thinkingmachines/inkling-small", "Thinking Machines: Inkling Small"),
			bm("openrouter/thinkingmachines/inkling-small:batch", "Thinking Machines: Inkling Small (batch)"),
			bm("openrouter/qwen/qwen3-coder-flash", "Qwen: Qwen3 Coder Flash"),
			bm("openrouter/mistralai/mistral-large-2512", "Mistral: Mistral Large 3 2512"),
			bm("openrouter/mistralai/mistral-large-2407", "Mistral Large 2407"),
			bm("openrouter/nvidia/nemotron-3-super-120b-a12b", "NVIDIA: Nemotron 3 Super"),
			bm("openrouter/mistralai/mistral-large", "Mistral Large"),
			bm("openrouter/nvidia/nemotron-3-ultra-550b-a55b:free", "NVIDIA: Nemotron 3 Ultra (free)"),
			bm("openrouter/openai/gpt-5.1-codex-mini", "OpenAI: GPT-5.1-Codex-Mini"),
			bm("openrouter/qwen/qwen3.5-plus-20260420", "Qwen: Qwen3.5 Plus 2026-04-20"),
			bm("openrouter/mistralai/mistral-small-2603", "Mistral: Mistral Small 4"),
			bm("openrouter/mistralai/devstral-2512", "Mistral: Devstral 2 2512"),
			bm("openrouter/mistralai/ministral-14b-2512", "Mistral: Ministral 3 14B 2512"),
			bm("openrouter/mistralai/ministral-3b-2512", "Mistral: Ministral 3 3B 2512"),
			bm("openrouter/mistralai/ministral-8b-2512", "Mistral: Ministral 3 8B 2512"),
			bm("openrouter/mistralai/codestral-2508", "Mistral: Codestral 2508"),
			bm("openrouter/mistralai/voxtral-small-24b-2507", "Mistral: Voxtral Small 24B 2507"),
			bm("openrouter/qwen/qwen3-235b-a22b-2507", "Qwen: Qwen3 235B A22B Instruct 2507"),
			bm("openrouter/qwen/qwen3-30b-a3b-instruct-2507", "Qwen: Qwen3 30B A3B Instruct 2507"),
			bm("openrouter/qwen/qwen3.5-plus-02-15", "Qwen: Qwen3.5 Plus 2026-02-15"),
			bm("openrouter/qwen/qwen-plus-2025-07-28", "Qwen: Qwen Plus 0728"),
			bm("openrouter/openai/gpt-4o-2024-11-20", "OpenAI: GPT-4o (2024-11-20)"),
			bm("openrouter/openai/gpt-4o-2024-08-06", "OpenAI: GPT-4o (2024-08-06)"),
			bm("openrouter/openai/gpt-4o-2024-05-13", "OpenAI: GPT-4o (2024-05-13)"),
			bm("openrouter/moonshotai/kimi-k2-0905", "MoonshotAI: Kimi K2 0905"),
			bm("openrouter/moonshotai/kimi-k2", "MoonshotAI: Kimi K2 0711"),
			bm("openrouter/deepseek/deepseek-r1-0528", "DeepSeek: R1 0528"),
			bm("openrouter/qwen/qwen3.5-397b-a17b", "Qwen: Qwen3.5 397B A17B"),
			bm("openrouter/deepseek/deepseek-chat-v3-0324", "DeepSeek: DeepSeek V3 0324"),
			bm("openrouter/qwen/qwen3-235b-a22b", "Qwen: Qwen3 235B A22B"),
			bm("openrouter/qwen/qwen3-vl-235b-a22b-instruct", "Qwen: Qwen3 VL 235B A22B Instruct"),
			bm("openrouter/openai/gpt-oss-120b", "OpenAI: gpt-oss-120b"),
			bm("openrouter/openai/gpt-oss-120b:batch", "OpenAI: gpt-oss-120b (batch)"),
			bm("openrouter/qwen/qwen3.8-2.4t-a95b", "Qwen: Qwen3.8 2.4T A95B"),
			bm("openrouter/qwen/qwen3.8-2.4t-a95b:batch", "Qwen: Qwen3.8 2.4T A95B (batch)"),
			bm("openrouter/qwen/qwen3-next-80b-a3b-instruct", "Qwen: Qwen3 Next 80B A3B Instruct"),
			bm("openrouter/qwen/qwen-2.5-72b-instruct", "Qwen2.5 72B Instruct"),
			bm("openrouter/meta-llama/llama-3.1-70b-instruct", "Meta: Llama 3.1 70B Instruct"),
			bm("openrouter/meta-llama/llama-3.3-70b-instruct", "Meta: Llama 3.3 70B Instruct"),
			bm("openrouter/sao10k/l3.1-euryale-70b", "Sao10K: Llama 3.1 Euryale 70B v2.2"),
			bm("openrouter/qwen/qwen3.6-35b-a3b", "Qwen: Qwen3.6 35B A3B"),
			bm("openrouter/qwen/qwen3-32b", "Qwen: Qwen3 32B"),
			bm("openrouter/qwen/qwen3-vl-32b-instruct", "Qwen: Qwen3 VL 32B Instruct"),
			bm("openrouter/google/gemma-4-31b-it", "Google: Gemma 4 31B"),
			bm("openrouter/google/gemma-4-31b-it:batch", "Google: Gemma 4 31B (batch)"),
			bm("openrouter/meta/muse-glimmer-30b", "Meta: Muse Glimmer 30B"),
			bm("openrouter/meta/muse-glimmer-30b:batch", "Meta: Muse Glimmer 30B (batch)"),
			bm("openrouter/qwen/qwen3-30b-a3b", "Qwen: Qwen3 30B A3B"),
			bm("openrouter/qwen/qwen3-vl-30b-a3b-instruct", "Qwen: Qwen3 VL 30B A3B Instruct"),
			bm("openrouter/cohere/command-r-08-2024", "Cohere: Command R (08-2024)"),
			bm("openrouter/cohere/command-r-plus-08-2024", "Cohere: Command R+ (08-2024)"),
			bm("openrouter/google/gemma-3-27b-it", "Google: Gemma 3 27B"),
			bm("openrouter/qwen/qwen3.6-27b", "Qwen: Qwen3.6 27B"),
			bm("openrouter/qwen/qwen3.8-27b", "Qwen: Qwen3.8 27B"),
			bm("openrouter/google/gemma-4-26b-a4b-it", "Google: Gemma 4 26B A4B "),
			bm("openrouter/mistralai/mistral-small-3.2-24b-instruct", "Mistral: Mistral Small 3.2 24B"),
			bm("openrouter/mistralai/mixtral-8x22b-instruct", "Mistral: Mixtral 8x22B Instruct"),
			bm("openrouter/openai/gpt-oss-20b", "OpenAI: gpt-oss-20b"),
			bm("openrouter/openai/gpt-oss-safeguard-20b", "OpenAI: gpt-oss-safeguard-20b"),
			bm("openrouter/qwen/qwen3-14b", "Qwen: Qwen3 14B"),
			bm("openrouter/google/gemma-3-12b-it", "Google: Gemma 3 12B"),
			bm("openrouter/thedrummer/unslopnemo-12b", "TheDrummer: UnslopNemo 12B"),
			bm("openrouter/qwen/qwen3.5-122b-a10b", "Qwen: Qwen3.5-122B-A10B"),
			bm("openrouter/ibm-granite/granite-4.2-8b", "IBM: Granite 4.2 8B"),
			bm("openrouter/meta-llama/llama-3.1-8b-instruct", "Meta: Llama 3.1 8B Instruct"),
			bm("openrouter/qwen/qwen3-8b", "Qwen: Qwen3 8B"),
			bm("openrouter/qwen/qwen3-vl-8b-instruct", "Qwen: Qwen3 VL 8B Instruct"),
			bm("openrouter/qwen/qwen-2.5-7b-instruct", "Qwen: Qwen2.5 7B Instruct"),
			bm("openrouter/openai/gpt-6-astra", "OpenAI: GPT-6 Astra"),
			bm("openrouter/openai/gpt-6-astra:batch", "OpenAI: GPT-6 Astra (batch)"),
			bm("openrouter/openai/gpt-5.6-luna", "OpenAI: GPT-5.6 Luna"),
			bm("openrouter/openai/gpt-5.6-luna:batch", "OpenAI: GPT-5.6 Luna (batch)"),
			bm("openrouter/openai/gpt-5.6-sol", "OpenAI: GPT-5.6 Sol"),
			bm("openrouter/openai/gpt-5.6-sol:batch", "OpenAI: GPT-5.6 Sol (batch)"),
			bm("openrouter/openai/gpt-5.6-terra", "OpenAI: GPT-5.6 Terra"),
			bm("openrouter/openai/gpt-5.6-terra:batch", "OpenAI: GPT-5.6 Terra (batch)"),
			bm("openrouter/openai/gpt-5.5", "OpenAI: GPT-5.5"),
			bm("openrouter/openai/gpt-5.5:batch", "OpenAI: GPT-5.5 (batch)"),
			bm("openrouter/openai/gpt-5.4", "OpenAI: GPT-5.4"),
			bm("openrouter/openai/gpt-5.4:batch", "OpenAI: GPT-5.4 (batch)"),
			bm("openrouter/z-ai/glm-5.3", "Z.ai: GLM 5.3"),
			bm("openrouter/openai/gpt-5.2", "OpenAI: GPT-5.2"),
			bm("openrouter/openai/gpt-5.2:batch", "OpenAI: GPT-5.2 (batch)"),
			bm("openrouter/openai/gpt-5.2-chat", "OpenAI: GPT-5.2 Chat"),
			bm("openrouter/z-ai/glm-5.2", "Z.ai: GLM 5.2"),
			bm("openrouter/openai/gpt-5.1", "OpenAI: GPT-5.1"),
			bm("openrouter/openai/gpt-5.1:batch", "OpenAI: GPT-5.1 (batch)"),
			bm("openrouter/z-ai/glm-5.1", "Z.ai: GLM 5.1"),
			bm("openrouter/openai/gpt-5", "OpenAI: GPT-5"),
			bm("openrouter/openai/gpt-5:batch", "OpenAI: GPT-5 (batch)"),
			bm("openrouter/z-ai/glm-5", "Z.ai: GLM 5"),
			bm("openrouter/x-ai/grok-4.20", "SpaceXAI: Grok 4.20"),
			bm("openrouter/z-ai/glm-4.7", "Z.ai: GLM 4.7"),
			bm("openrouter/x-ai/grok-4.6", "SpaceXAI: Grok 4.6"),
			bm("openrouter/z-ai/glm-4.6", "Z.ai: GLM 4.6"),
			bm("openrouter/z-ai/glm-4.6v", "Z.ai: GLM 4.6V"),
			bm("openrouter/x-ai/grok-4.5", "SpaceXAI: Grok 4.5"),
			bm("openrouter/z-ai/glm-4.5", "Z.ai: GLM 4.5"),
			bm("openrouter/z-ai/glm-4.5-air", "Z.ai: GLM 4.5 Air"),
			bm("openrouter/z-ai/glm-4.5v", "Z.ai: GLM 4.5V"),
			bm("openrouter/x-ai/grok-4.3", "SpaceXAI: Grok 4.3"),
			bm("openrouter/x-ai/grok-4.3:batch", "SpaceXAI: Grok 4.3 (batch)"),
			bm("openrouter/openai/gpt-4.1", "OpenAI: GPT-4.1"),
			bm("openrouter/openai/gpt-4.1:batch", "OpenAI: GPT-4.1 (batch)"),
			bm("openrouter/meta-llama/llama-4-maverick", "Meta: Llama 4 Maverick"),
			bm("openrouter/meta-llama/llama-4-scout", "Meta: Llama 4 Scout"),
			bm("openrouter/openai/gpt-4", "OpenAI: GPT-4"),
			bm("openrouter/openai/gpt-4o", "OpenAI: GPT-4o"),
			bm("openrouter/openai/gpt-4o:batch", "OpenAI: GPT-4o (batch)"),
			bm("openrouter/tencent/hy4-preview", "Tencent: Hy4 preview"),
			bm("openrouter/qwen/qwen3.7-plus", "Qwen: Qwen3.7 Plus"),
			bm("openrouter/qwen/qwen3.6-plus", "Qwen: Qwen3.6 Plus"),
			bm("openrouter/qwen/qwen3.5-35b-a3b", "Qwen: Qwen3.5-35B-A3B"),
			bm("openrouter/qwen/qwen3.5-27b", "Qwen: Qwen3.5-27B"),
			bm("openrouter/qwen/qwen3.5-9b", "Qwen: Qwen3.5-9B"),
			bm("openrouter/qwen/qwen3.5-9b:batch", "Qwen: Qwen3.5-9B (batch)"),
			bm("openrouter/mistralai/mistral-medium-3-5", "Mistral: Mistral Medium 3.5"),
			bm("openrouter/mistralai/mistral-medium-3-5:batch", "Mistral: Mistral Medium 3.5 (batch)"),
			bm("openrouter/nvidia/nemotron-3.5-lightning", "NVIDIA: Nemotron 3.5 Lightning"),
			bm("openrouter/deepseek/deepseek-v3.2", "DeepSeek: DeepSeek V3.2"),
			bm("openrouter/deepseek/deepseek-v3.2-exp", "DeepSeek: DeepSeek V3.2 Exp"),
			bm("openrouter/deepseek/deepseek-chat-v3.1", "DeepSeek: DeepSeek V3.1"),
			bm("openrouter/deepseek/deepseek-v3.1-terminus", "DeepSeek: DeepSeek V3.1 Terminus"),
			bm("openrouter/mistralai/mistral-medium-3.1", "Mistral: Mistral Medium 3.1"),
			bm("openrouter/aion-labs/aion-3.0", "AionLabs: Aion-3.0"),
			bm("openrouter/deepseek/deepseek-chat", "DeepSeek: DeepSeek V3"),
			bm("openrouter/minimax/minimax-m3", "MiniMax: MiniMax M3"),
			bm("openrouter/minimax/minimax-m3:batch", "MiniMax: MiniMax M3 (batch)"),
			bm("openrouter/mistralai/mistral-medium-3", "Mistral: Mistral Medium 3"),
			bm("openrouter/moonshotai/kimi-k3", "MoonshotAI: Kimi K3"),
			bm("openrouter/moonshotai/kimi-k3:batch", "MoonshotAI: Kimi K3 (batch)"),
			bm("openrouter/openai/o3", "OpenAI: o3"),
			bm("openrouter/openai/o3:batch", "OpenAI: o3 (batch)"),
			bm("openrouter/tencent/hy3", "Tencent: Hy3"),
			bm("openrouter/tencent/hy3-preview", "Tencent: Hy3 preview"),
			bm("openrouter/minimax/minimax-m2.7", "MiniMax: MiniMax M2.7"),
			bm("openrouter/moonshotai/kimi-k2.6", "MoonshotAI: Kimi K2.6"),
			bm("openrouter/inception/mercury-2.5-preview", "Inception: Mercury 2.5 Preview"),
			bm("openrouter/minimax/minimax-m2.5", "MiniMax: MiniMax M2.5"),
			bm("openrouter/moonshotai/kimi-k2.5", "MoonshotAI: Kimi K2.5"),
			bm("openrouter/xiaomi/mimo-v2.5", "Xiaomi: MiMo-V2.5"),
			bm("openrouter/minimax/minimax-m2.1", "MiniMax: MiniMax M2.1"),
			bm("openrouter/poolside/laguna-s-2.1", "Poolside: Laguna S 2.1"),
			bm("openrouter/poolside/laguna-xs-2.1", "Poolside: Laguna XS 2.1"),
			bm("openrouter/aion-labs/aion-2.0", "AionLabs: Aion-2.0"),
			bm("openrouter/inception/mercury-2", "Inception: Mercury 2"),
			bm("openrouter/meituan/longcat-2.0", "Meituan: LongCat 2.0"),
			bm("openrouter/minimax/minimax-m2", "MiniMax: MiniMax M2"),
			bm("openrouter/bytedance-seed/seed-1.6", "ByteDance Seed: Seed 1.6"),
			bm("openrouter/meta/muse-spark-1.3", "Meta: Muse Spark 1.3"),
			bm("openrouter/meta/muse-spark-1.3-contributor", "Meta: Muse Spark 1.3 Contributor"),
			bm("openrouter/meta/muse-spark-1.2", "Meta: Muse Spark 1.2"),
			bm("openrouter/meta/muse-spark-1.2-contributor", "Meta: Muse Spark 1.2 Contributor"),
			bm("openrouter/meta/muse-spark-1.1", "Meta: Muse Spark 1.1"),
			bm("openrouter/deepseek/deepseek-r1", "DeepSeek: R1"),
			bm("openrouter/minimax/minimax-m1", "MiniMax: MiniMax M1"),
			bm("openrouter/openai/o1", "OpenAI: o1"),
			bm("openrouter/x-ai/grok-build-0.1", "SpaceXAI: Grok Build 0.1"),
			bm("openrouter/auto", "Auto"),
			bm("openrouter/openrouter/auto", "Auto Router"),
			bm("openrouter/openrouter/auto-beta", "Auto Router (Beta)"),
			bm("openrouter/mistralai/mistral-nemo", "Mistral: Mistral Nemo"),
			bm("openrouter/mistralai/mistral-saba", "Mistral: Saba"),
			bm("openrouter/~moonshotai/kimi-latest", "MoonshotAI Kimi Latest"),
			bm("openrouter/~openai/gpt-latest", "OpenAI GPT Latest"),
			bm("openrouter/openai/gpt-audio", "OpenAI: GPT Audio"),
			bm("openrouter/openai/gpt-chat-latest", "OpenAI: GPT Chat Latest"),
			bm("openrouter/openrouter/fusion", "OpenRouter: Fusion"),
			bm("openrouter/qwen/qwen-plus", "Qwen: Qwen-Plus"),
			bm("openrouter/rekaai/reka-edge", "Reka Edge"),
			bm("openrouter/relace/relace-search", "Relace: Relace Search"),
			bm("openrouter/sakana/sakana-namazu", "Sakana: Sakana Namazu"),
			bm("openrouter/~x-ai/grok-latest", "xAI: Grok Latest"),
			bm("openrouter/~z-ai/glm-latest", "Z.ai: GLM Latest"),
			bm("openrouter/thinkingmachines/inkling:free", "Thinking Machines: Inkling (free)"),
			bm("openrouter/thinkingmachines/inkling-small:free", "Thinking Machines: Inkling Small (free)"),
			bm("openrouter/deepseek/deepseek-v4-flash-0731", "DeepSeek: DeepSeek V4 Flash 0731"),
			bm("openrouter/deepseek/deepseek-v4-flash-0731:batch", "DeepSeek: DeepSeek V4 Flash 0731 (batch)"),
			bm("openrouter/openai/gpt-3.5-turbo-0613", "OpenAI: GPT-3.5 Turbo (older v0613)"),
			bm("openrouter/deepseek/deepseek-v4-flash", "DeepSeek: DeepSeek V4 Flash 0423"),
			bm("openrouter/openai/gpt-3.5-turbo-16k", "OpenAI: GPT-3.5 Turbo 16k"),
			bm("openrouter/z-ai/glm-5.3-flash", "Z.ai: GLM 5.3 Flash"),
			bm("openrouter/z-ai/glm-5.3-flash:batch", "Z.ai: GLM 5.3 Flash (batch)"),
			bm("openrouter/z-ai/glm-5-turbo", "Z.ai: GLM 5 Turbo"),
			bm("openrouter/z-ai/glm-5v-turbo", "Z.ai: GLM 5V Turbo"),
			bm("openrouter/z-ai/glm-4.7-flash", "Z.ai: GLM 4.7 Flash"),
			bm("openrouter/~deepseek/deepseek-v4-flash-latest", "DeepSeek V4 Flash Latest"),
			bm("openrouter/deepseek/deepseek-v4-flash-vision-exp", "DeepSeek: DeepSeek V4 Flash Vision Exp"),
			bm("openrouter/openai/gpt-4-turbo", "OpenAI: GPT-4 Turbo"),
			bm("openrouter/openai/gpt-4-turbo:batch", "OpenAI: GPT-4 Turbo (batch)"),
			bm("openrouter/openai/gpt-4-turbo-preview", "OpenAI: GPT-4 Turbo Preview"),
			bm("openrouter/google/gemini-3.8-flash", "Google: Gemini 3.8 Flash"),
			bm("openrouter/google/gemini-3.8-flash:batch", "Google: Gemini 3.8 Flash (batch)"),
			bm("openrouter/qwen/qwen3.8-flash", "Qwen: Qwen3.8 Flash"),
			bm("openrouter/google/gemini-3.7-flash", "Google: Gemini 3.7 Flash"),
			bm("openrouter/google/gemini-3.7-flash:batch", "Google: Gemini 3.7 Flash (batch)"),
			bm("openrouter/qwen/qwen3.7-flash", "Qwen: Qwen3.7 Flash"),
			bm("openrouter/stepfun/step-3.7-flash", "StepFun: Step 3.7 Flash"),
			bm("openrouter/google/gemini-3.6-flash", "Google: Gemini 3.6 Flash"),
			bm("openrouter/google/gemini-3.6-flash:batch", "Google: Gemini 3.6 Flash (batch)"),
			bm("openrouter/qwen/qwen3.6-flash", "Qwen: Qwen3.6 Flash"),
			bm("openrouter/google/gemini-3.5-flash", "Google: Gemini 3.5 Flash"),
			bm("openrouter/google/gemini-3.5-flash:batch", "Google: Gemini 3.5 Flash (batch)"),
			bm("openrouter/openai/gpt-3.5-turbo", "OpenAI: GPT-3.5 Turbo"),
			bm("openrouter/openai/gpt-3.5-turbo:batch", "OpenAI: GPT-3.5 Turbo (batch)"),
			bm("openrouter/qwen/qwen3.5-flash-02-23", "Qwen: Qwen3.5-Flash"),
			bm("openrouter/stepfun/step-3.5-flash", "StepFun: Step 3.5 Flash"),
			bm("openrouter/google/gemini-3-flash-preview", "Google: Gemini 3 Flash Preview"),
			bm("openrouter/google/gemini-3-flash-preview:batch", "Google: Gemini 3 Flash Preview (batch)"),
			bm("openrouter/inclusionai/ling-3.0-flash", "inclusionAI: Ling 3.0 Flash"),
			bm("openrouter/inclusionai/ling-3.0-flash-fin", "inclusionAI: Ling 3.0 Flash Fin"),
			bm("openrouter/google/gemini-2.5-flash", "Google: Gemini 2.5 Flash"),
			bm("openrouter/google/gemini-2.5-flash:batch", "Google: Gemini 2.5 Flash (batch)"),
			bm("openrouter/bytedance-seed/seed-2-1-turbo", "ByteDance Seed: Seed 2.1 Turbo"),
			bm("openrouter/bytedance-seed/seed-1.6-flash", "ByteDance Seed: Seed 1.6 Flash"),
			bm("openrouter/~google/gemini-flash-latest", "Google Gemini Flash Latest"),
			bm("openrouter/~z-ai/glm-flash-latest", "Z.ai: GLM Flash Latest"),
			bm("openrouter/nvidia/nemotron-3-super-120b-a12b:free", "NVIDIA: Nemotron 3 Super (free)"),
			bm("openrouter/openai/gpt-4o-mini-2024-07-18", "OpenAI: GPT-4o-mini (2024-07-18)"),
			bm("openrouter/nvidia/nemotron-3-nano-30b-a3b", "NVIDIA: Nemotron 3 Nano 30B A3B"),
			bm("openrouter/openai/gpt-5.4-mini", "OpenAI: GPT-5.4 Mini"),
			bm("openrouter/openai/gpt-5.4-mini:batch", "OpenAI: GPT-5.4 Mini (batch)"),
			bm("openrouter/openai/gpt-5.4-nano", "OpenAI: GPT-5.4 Nano"),
			bm("openrouter/openai/gpt-5.4-nano:batch", "OpenAI: GPT-5.4 Nano (batch)"),
			bm("openrouter/openai/gpt-5-mini", "OpenAI: GPT-5 Mini"),
			bm("openrouter/openai/gpt-5-mini:batch", "OpenAI: GPT-5 Mini (batch)"),
			bm("openrouter/openai/gpt-5-nano", "OpenAI: GPT-5 Nano"),
			bm("openrouter/openai/gpt-5-nano:batch", "OpenAI: GPT-5 Nano (batch)"),
			bm("openrouter/openai/gpt-4.1-mini", "OpenAI: GPT-4.1 Mini"),
			bm("openrouter/openai/gpt-4.1-mini:batch", "OpenAI: GPT-4.1 Mini (batch)"),
			bm("openrouter/openai/gpt-4.1-nano", "OpenAI: GPT-4.1 Nano"),
			bm("openrouter/openai/gpt-4.1-nano:batch", "OpenAI: GPT-4.1 Nano (batch)"),
			bm("openrouter/openai/gpt-4o-mini", "OpenAI: GPT-4o-mini"),
			bm("openrouter/openai/gpt-4o-mini:batch", "OpenAI: GPT-4o-mini (batch)"),
			bm("openrouter/openai/o4-mini", "OpenAI: o4 Mini"),
			bm("openrouter/openai/o4-mini:batch", "OpenAI: o4 Mini (batch)"),
			bm("openrouter/openai/o4-mini-high", "OpenAI: o4 Mini High"),
			bm("openrouter/aion-labs/aion-3.0-mini", "AionLabs: Aion-3.0-Mini"),
			bm("openrouter/openai/o3-mini", "OpenAI: o3 Mini"),
			bm("openrouter/openai/o3-mini:batch", "OpenAI: o3 Mini (batch)"),
			bm("openrouter/openai/o3-mini-high", "OpenAI: o3 Mini High"),
			bm("openrouter/amazon/nova-2-lite-v1", "Amazon: Nova 2 Lite"),
			bm("openrouter/bytedance-seed/seed-2.0-lite", "ByteDance Seed: Seed-2.0-Lite"),
			bm("openrouter/bytedance-seed/seed-2.0-mini", "ByteDance Seed: Seed-2.0-Mini"),
			bm("openrouter/nex-agi/nex-n2-mini", "Nex AGI: Nex-N2-Mini"),
			bm("openrouter/amazon/nova-lite-v1", "Amazon: Nova Lite 1.0"),
			bm("openrouter/amazon/nova-micro-v1", "Amazon: Nova Micro 1.0"),
			bm("openrouter/cohere/north-mini-code:free", "Cohere: North Mini Code (free)"),
			bm("openrouter/~openai/gpt-mini-latest", "OpenAI GPT Mini Latest"),
			bm("openrouter/openai/gpt-audio-mini", "OpenAI: GPT Audio Mini"),
			bm("openrouter/google/gemma-4-31b-it:free", "Google: Gemma 4 31B (free)"),
			bm("openrouter/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", "NVIDIA: Nemotron 3 Nano Omni (free)"),
			bm("openrouter/google/gemma-4-26b-a4b-it:free", "Google: Gemma 4 26B A4B  (free)"),
			bm("openrouter/z-ai/glm-5.2:free", "Z.ai: GLM 5.2 (free)"),
			bm("openrouter/nvidia/nemotron-3.5-lightning:free", "NVIDIA: Nemotron 3.5 Lightning (free)"),
			bm("openrouter/dots-studio/dots-3-note-preview:free", "Dots Studio: Dots3-Note Preview (free)"),
			bm("openrouter/minimax/minimax-m3:free", "MiniMax: MiniMax M3 (free)"),
			bm("openrouter/minimax/minimax-m2.7:free", "MiniMax: MiniMax M2.7 (free)"),
			bm("openrouter/liquid/lfm-2.5-2.6b:free", "LiquidAI: LFM2.5-2.6B (free)"),
			bm("openrouter/poolside/laguna-s-2.1:free", "Poolside: Laguna S 2.1 (free)"),
			bm("openrouter/poolside/laguna-xs-2.1:free", "Poolside: Laguna XS 2.1 (free)"),
			bm("openrouter/openrouter/free", "Free Models Router"),
			bm("openrouter/google/gemini-3.5-flash-lite", "Google: Gemini 3.5 Flash Lite"),
			bm("openrouter/google/gemini-3.5-flash-lite:batch", "Google: Gemini 3.5 Flash Lite (batch)"),
			bm("openrouter/google/gemini-3.1-flash-lite", "Google: Gemini 3.1 Flash Lite"),
			bm("openrouter/google/gemini-3.1-flash-lite:batch", "Google: Gemini 3.1 Flash Lite (batch)"),
			bm("openrouter/google/gemini-3.1-flash-lite-preview", "Google: Gemini 3.1 Flash Lite Preview"),
			bm("openrouter/google/gemini-2.5-flash-lite", "Google: Gemini 2.5 Flash Lite"),
			bm("openrouter/google/gemini-2.5-flash-lite:batch", "Google: Gemini 2.5 Flash Lite (batch)"),
			bm("openrouter/inclusionai/ling-3.0-flash-fin:free", "inclusionAI: Ling 3.0 Flash Fin (free)"),
			bm("openrouter/inclusionai/ling-3.0-flash-sante:free", "inclusionAI: Ling 3.0 Flash Sante (free)"),
		},
	},
	{
		ID: "openai", Label: "OpenAI", Default: "openai/gpt-5.5",
		Models: []builtinModel{
			bm("openai/gpt-5.5-pro", "GPT-5.5 Pro"),
			bm("openai/gpt-5.4-pro", "GPT-5.4 Pro"),
			bm("openai/gpt-5.2-pro", "GPT-5.2 Pro"),
			bm("openai/gpt-5-pro", "GPT-5 Pro"),
			bm("openai/o3-pro", "o3-pro"),
			bm("openai/o1-pro", "o1-pro"),
			bm("openai/gpt-5.3-codex", "GPT-5.3 Codex"),
			bm("openai/gpt-5.3-codex-spark", "GPT-5.3 Codex Spark"),
			bm("openai/gpt-4o-2024-11-20", "GPT-4o (2024-11-20)"),
			bm("openai/gpt-4o-2024-08-06", "GPT-4o (2024-08-06)"),
			bm("openai/gpt-4o-2024-05-13", "GPT-4o (2024-05-13)"),
			bm("openai/gpt-6-astra", "GPT-6 Astra"),
			bm("openai/gpt-5.6-luna", "GPT-5.6 Luna"),
			bm("openai/gpt-5.6-sol", "GPT-5.6 Sol"),
			bm("openai/gpt-5.6-terra", "GPT-5.6 Terra"),
			bm("openai/gpt-5.5", "GPT-5.5"),
			bm("openai/gpt-5.4", "GPT-5.4"),
			bm("openai/gpt-5.3-chat-latest", "GPT-5.3 Chat (latest)"),
			bm("openai/gpt-5.2", "GPT-5.2"),
			bm("openai/gpt-5.2-chat-latest", "GPT-5.2 Chat"),
			bm("openai/gpt-5.1", "GPT-5.1"),
			bm("openai/gpt-5", "GPT-5"),
			bm("openai/gpt-5-chat-latest", "GPT-5 Chat Latest"),
			bm("openai/gpt-4.1", "GPT-4.1"),
			bm("openai/gpt-4", "GPT-4"),
			bm("openai/gpt-4o", "GPT-4o"),
			bm("openai/o3", "o3"),
			bm("openai/gpt-realtime-2.1", "GPT-Realtime-2.1"),
			bm("openai/o1", "o1"),
			bm("openai/gpt-4-turbo", "GPT-4 Turbo"),
			bm("openai/gpt-5.4-mini", "GPT-5.4 mini"),
			bm("openai/gpt-5.4-nano", "GPT-5.4 nano"),
			bm("openai/gpt-5-mini", "GPT-5 Mini"),
			bm("openai/gpt-5-nano", "GPT-5 Nano"),
			bm("openai/gpt-4.1-mini", "GPT-4.1 mini"),
			bm("openai/gpt-4.1-nano", "GPT-4.1 nano"),
			bm("openai/gpt-4o-mini", "GPT-4o mini"),
			bm("openai/o4-mini", "o4-mini"),
			bm("openai/o3-mini", "o3-mini"),
		},
	},
	{
		ID: "anthropic", Label: "Anthropic", Default: "anthropic/claude-opus-4-8",
		Models: []builtinModel{
			bm("anthropic/claude-fable-5-1", "Claude Fable 5.1"),
			bm("anthropic/claude-fable-5", "Claude Fable 5"),
			bm("anthropic/claude-opus-4-5-20251101", "Claude Opus 4.5"),
			bm("anthropic/claude-opus-5", "Claude Opus 5"),
			bm("anthropic/claude-opus-4-8", "Claude Opus 4.8"),
			bm("anthropic/claude-opus-4-7", "Claude Opus 4.7"),
			bm("anthropic/claude-opus-4-6", "Claude Opus 4.6"),
			bm("anthropic/claude-opus-4-5", "Claude Opus 4.5 (latest)"),
			bm("anthropic/claude-sonnet-4-5-20250929", "Claude Sonnet 4.5"),
			bm("anthropic/claude-sonnet-5", "Claude Sonnet 5"),
			bm("anthropic/claude-sonnet-4-6", "Claude Sonnet 4.6"),
			bm("anthropic/claude-sonnet-4-5", "Claude Sonnet 4.5 (latest)"),
			bm("anthropic/claude-haiku-4-5-20251001", "Claude Haiku 4.5"),
			bm("anthropic/claude-haiku-4-5", "Claude Haiku 4.5 (latest)"),
		},
	},
	{
		ID: "google", Label: "Google", Default: "google/gemini-3.1-pro-preview",
		Models: []builtinModel{
			bm("google/deep-research-max-preview-04-2026", "Deep Research Max Preview (Apr-21-2026)"),
			bm("google/gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview"),
			bm("google/gemini-3.1-pro-preview-customtools", "Gemini 3.1 Pro Preview Custom Tools"),
			bm("google/gemini-2.5-pro", "Gemini 2.5 Pro"),
			bm("google/deep-research-preview-04-2026", "Deep Research Preview (Apr-21-2026)"),
			bm("google/gemma-4-31b-it", "Gemma 4 31B IT"),
			bm("google/gemini-2.5-computer-use-preview-10-2025", "Gemini 2.5 Computer Use Preview 10-2025"),
			bm("google/gemma-4-26b-a4b-it", "Gemma 4 26B A4B IT"),
			bm("google/gemini-3.8-flash", "Gemini 3.8 Flash"),
			bm("google/gemini-3.7-flash", "Gemini 3.7 Flash"),
			bm("google/gemini-3.6-flash", "Gemini 3.6 Flash"),
			bm("google/gemini-3.5-flash", "Gemini 3.5 Flash"),
			bm("google/gemini-3.1-flash-live-preview", "Gemini 3.1 Flash Live Preview"),
			bm("google/gemini-3-flash-preview", "Gemini 3 Flash Preview"),
			bm("google/gemini-2.5-flash", "Gemini 2.5 Flash"),
			bm("google/gemini-flash-latest", "Gemini Flash Latest"),
			bm("google/gemini-3.5-flash-lite", "Gemini 3.5 Flash Lite"),
			bm("google/gemini-3.1-flash-lite", "Gemini 3.1 Flash Lite"),
			bm("google/gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview"),
			bm("google/gemini-3.1-flash-lite-image", "Nano Banana 2 Lite"),
			bm("google/gemini-2.5-flash-lite", "Gemini 2.5 Flash-Lite"),
			bm("google/gemini-flash-lite-latest", "Gemini Flash-Lite Latest"),
		},
	},
	{
		ID: "xai", Label: "xAI", Default: "xai/grok-4.6",
		Models: []builtinModel{
			bm("xai/grok-4.6", "Grok 4.6"),
			bm("xai/grok-4.5", "Grok 4.5"),
			bm("xai/grok-4.3", "Grok 4.3"),
		},
	},
	{
		ID: "xiaomi", Label: "Xiaomi", Default: "xiaomi/mimo-v2.5-pro",
		Models: []builtinModel{
			bm("xiaomi/mimo-v2.5-pro", "MiMo-V2.5-Pro"),
			bm("xiaomi/mimo-v2.5-pro-ultraspeed", "MiMo-V2.5-Pro-UltraSpeed"),
			bm("xiaomi/mimo-v2.5", "MiMo-V2.5"),
		},
	},
}
